### ISSUE TITLE
The most correct way to copy cover art from one song to another?

### ISSUE THREAD

**Issue by ZYinMD** [Zazama/node-id3#93] opened 2020-11-01 19:10 UTC
In part of my workflow, I copy the cover art from song A to song B:
```js
function copyArt(pathToSongA, pathToSongB) {
  const tagsA = NodeID3.read(pathToSongA);
  NodeID3.update({ image: tagsA.image }, pathToSongB);
}
```

It works as intended, but then in [MP3 Diags](https://www.google.com/search?&q=MP3+Diags) (a software on windows that I've been using for many years), song B will be detected to have gotten new errors:
> ID3V2 tag has an APIC frame (which is used to store images), but the image couldn't be loaded.
> Unsupported text encoding for APIC frame in ID3V2 tag.

It's just some theoretical incorrectness detected by this software, and doesn't seem to have any practical effect, because in other software (e.g. Foobar2000 and Mp3tag), the new cover art of song B shows up correctly.

Is there a more correct way to write my code which doesn't produce this error?

Thanks!

**Comment by Zazama** [comment] 2020-11-01 20:48
Hey, would you mind sending me an example song A & B to jan.metzger@gmx.net? I'll checkout the MP3 Diags message.

**Comment by ZYinMD** [comment] 2020-11-01 21:38
Just sent. Thanks!

**Comment by Zazama** [comment] 2020-11-01 23:38
I've looked into the file and everything seems to be fine, I think the problem is found in MP3 Diag's source code: https://github.com/miracle2k/mp3diags/blob/77b419ae9c603d3d5a30a221875a1ea3f7bbab90/src/Id3V2Stream.cpp#L996

```cpp
MP3_CHECK (0 == pData[0] || 3 == pData[0], pos, id3v2UnsupApicTextEnc, NotSupTextEnc()); // !!! there's no need for StreamIsUnsupported here, because this error is not fatal, and it isn't allowed to propagate, therefore doesn't cause a stream to be Unsupported; //ttt2 review, support
szMimeType = pData + 1; // ttt3 type 0 is Latin1, while type 3 is UTF8, so this isn't quite right; however, MIME types should probably be plain ASCII, so it's the same; and anyway, we only recognize JPEG and PNG, which are ASCII
```

The first line basically checks if the encoding is UTF-8 or ASCII and if not, MP3_CHECK will throw an exception (id3v2UnsupApicTextEnc in this case), as can be read in the comment of the second line.
By spec, there's no such limitation for the picture frame and node-id3 will use its default encoding UTF-16, which will fail the MP3_CHECK line but is still correct (=> correctly read in other software).

See https://sourceforge.net/p/mp3diags/discussion/947206/thread/cb3417ae/

**Comment by ZYinMD** [comment] 2020-11-02 04:07
Thanks so much!! Your reply is awe-inspiring in multiple ways.

Yes it doesn't make any practical difference. The only problem for me is now I can't use the "auto fix" button in MP3 Diag, because doing so will "fix" the error by deleting the image altogether.

The good news is, I just found if I drag the affected files into [Mp3tag](https://www.google.com/search?&q=Mp3tag), then hit "save", this error will disappear. So, I'll add this manual step into my workflow.

**Comment by Zazama** [comment] 2020-11-09 21:47
I'll close this issue for now, but I'm glad I could help!

I might add the possibility to choose the encoding for all/specific frames at a later time, until then, I hope your workflow solves the problem 👍 If not, feel free to open another issue (or reopen this).

**Closed by Zazama** 2020-11-09 21:47 UTC
