### ISSUE TITLE
image in ID3-tag gone or corrupted after update

### ISSUE THREAD

**Issue by CrossmodGlennVS** [Zazama/node-id3#109] opened 2021-04-29 20:52 UTC
After updating ID3-tags 'artist' and 'title', the cover image is gone.
Even though the image property is still in the ID3-tag (after reading again everything looks ok), the thumbnail shown in my filebrowser is.

This happened on a Mac computer.

Any ideas why this happens?

**Comment by Zazama** [comment] 2021-04-29 22:35
Hey, can you try to replace the src/ID3Util.js with the current master branch file?
I hope it fixes your issue (will also be published to npm tomorrow). Otherwise feel free to send me the mp3 you're having problems with to jan.metzger@gmx.net

**Comment by jin60641** [comment] 2021-04-30 01:39
duplicate of https://github.com/Zazama/node-id3/issues/105

**Comment by CrossmodGlennVS** [comment] 2021-04-30 04:29
I copy pasted the code from src/ID3Util.js (updated 3 days ago).

I don't use iTunes (#105 looks like another problem) and it looks like the ID3-tag is the same as before it was updated. Except that de comment/COMM property changed from undefined to '' after update, maybe this is not the problem.

Maybe this is a Mac problem. What's a recommended ID3-tagreader program to check this with aswell?

**Comment by jin60641** [comment] 2021-04-30 05:16
oh, sorry.
you can use mp3tag for mac free trial 7 days.

**Comment by CrossmodGlennVS** [comment] 2021-05-01 12:15
The cover image is not visible in mp3tag either.
I'm stuck.

**Comment by Zazama** [comment] 2021-05-01 12:27
Can you send me the mp3 (if you have it, before and after) to jan.metzger@gmx.net?
And the code snippet you've used if possible

**Comment by Zazama** [comment] 2021-05-12 12:03
Problem was #105 (fixed by 0.2.3)

**Closed by Zazama** 2021-05-12 12:03 UTC
